module.exports = {
    YOUTUBE: {
        NEW_UPLOAD:         "YOUTUBE:UPLOAD", 
        NEW_STREAM:         "YOUTUBE:LIVE",
        NEW_RESERVATION:    "YOUTUBE:RESERVATION",

        RESERVATION_LIVE:   "YOUTUBE:LIVE",
        RESERVATION_MOVED:  "YOUTUBE:RESERVATION_MOVED",
        STREAM_OFFLINE:     "YOUTUBE:OFFLINE",

        COMMUNITY_POST:     "YOUTUBE:COMMUNITY_POST"
    },
    TWITCASTING: {
        LIVE: "TWITCASTING:LIVE",
        OFFLINE: "TWITCASTING:OFFLINE"
    },
    TWITCH: {
        LIVE: "TWITCH:LIVE",
        OFFLINE: "TWITCH:OFFLINE"
    }
}