api:
  host: "your-domain.edu"
  port: 3000

throttler:
  ttl: 10  # default time to live for cached request IPs
  limit: 10  # requests/ttl allowed before too many requests is returned.

youtube:
  quotaLimit: 10000 # daily YouTube API quota limit; used to determine polling intervals
  usableQuota: 1 # percentage of the above quota the interval is allowed to use.

graphql:
  introspection: true # enable introspection requests
  playground: true    # enable playground (GET /graphql by default)