api:
  host: "your-domain.edu"
  port: 3000

youtube:
  quotaLimit: 10000 # daily YouTube API quota limit; used to determine polling intervals
  usableQuota: 1 # percentage of the above quota the interval is allowed to use.